version: '3'

volumes:
  term_project_local_postgres_data: {}
  term_project_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: term_project_local_django
    container_name: term_project_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: term_project_production_postgres
    container_name: term_project_local_postgres
    volumes:
      - term_project_local_postgres_data:/var/lib/postgresql/data
      - term_project_local_postgres_data_backups:/backups
    ports:
      - '5432:5432'
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: term_project_local_redis

  celeryworker:
    <<: *django
    image: term_project_local_celeryworker
    container_name: term_project_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: term_project_local_celerybeat
    container_name: term_project_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

